# Generated by Django 2.0.5 on 2018-10-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20181011_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='title',
        ),
    ]
