# Generated by Django 2.0.5 on 2018-10-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20181011_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='title',
            new_name='text',
        ),
    ]
