# Generated by Django 2.0.5 on 2018-10-17 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0029_auto_20181017_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='status',
            new_name='Status',
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Choice'),
        ),
    ]
